# fly.toml app configuration file generated for gitdiagram-fi on 2026-05-08T06:47:22Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gitdiagram-fi'
primary_region = 'sin'

[build]

[env]
  NEXT_PUBLIC_GENERATION_BACKEND = 'next'
  NODE_ENV = 'production'
  PORT = '3000'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '15s'
    timeout = '5s'
    grace_period = '30s'
    method = 'GET'
    path = '/'

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 2
  memory_mb = 2048
